package model;
// Generated Mar 17, 2017 4:12:56 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Source generated by hbm2java
 */
@Entity
@Table
public class Source implements Serializable {

    @Id
    @Column(nullable = false, length = 8, unique = true)
    private Integer sourceId;
    @Column(nullable = true, length = 100)
    private String tag;
    @Column(nullable = true)
    private double rateNumber;
    @Column(nullable = true)
    private int numOfRate;
    @Column(nullable = true)
    private int numOfView;

    public Integer getSourceId() {
        return sourceId;
    }

    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    public double getRateNumber() {
        return rateNumber;
    }

    public void setRateNumber(double rateNumber) {
        this.rateNumber = rateNumber;
    }


    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }


    public int getNumOfRate() {
        return numOfRate;
    }

    public void setNumOfRate(int numOfRate) {
        this.numOfRate = numOfRate;
    }

    public int getNumOfView() {
        return numOfView;
    }

    public void setNumOfView(int numOfView) {
        this.numOfView = numOfView;
    }

    
}
