package model;
// Generated Mar 17, 2017 4:12:56 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * User generated by hbm2java
 */
@Entity
public class User implements Serializable{
    @Id
    @GeneratedValue(strategy = GenerationType.TABLE)
    @Column (nullable = false,length = 8,unique = true)
    private Integer userId;
    @Column (nullable = false,length = 40)
    private String firstName;
    @Column (nullable = false,length = 40)
    private String lastName;
    @Column (nullable = false,length = 80,unique = true)
    private String email;
    @Column (nullable = false,length = 40)
    private String password;
    private Boolean activate;
    @Basic(fetch=FetchType.LAZY)
    @Column (nullable = true, columnDefinition = "LONGBLOB" )
    private byte[] img;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getActivate() {
        return activate;
    }

    public void setActivate(Boolean activate) {
        this.activate = activate;
    }

    public byte[] getImg() {
        return img;
    }

    public void setImg(byte[] img) {
        this.img = img;
    }
    
}
